USE MannschaftDB;

DROP TABLE IF EXISTS receivesPenalty;
DROP TABLE IF EXISTS monthlyPay;
DROP TABLE IF EXISTS specialPay;

DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS penalties;
DROP TABLE IF EXISTS contributions;
DROP TABLE IF EXISTS expenses;
